spring:
  application:
    name: orders-events-service
  profiles:
    default: local
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: com.arthurrocha.ordersevents.events
        spring.json.value.default.type: com.arthurrocha.ordersevents.events.OrderEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
  jpa:
    open-in-view: false
  flyway:
    enabled: true
  docker:
    compose:
      enabled: true
