spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:mydatabase}
    username: ${POSTGRES_USER:myuser}
    password: ${POSTGRES_PASSWORD:secret}
